# Generated by Django 2.2.4 on 2021-04-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='description',
            field=models.TextField(default='something', max_length=50),
        ),
    ]
